spring.application.name=car-repair
server.port=9081
springdoc.api-docs.path=/api-docs
# Dados do banco
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/car-repair
##spring.datasource.password=874802c381d14d54b217c598f440072f
spring.datasource.password=12345678
spring.datasource.username=postgres
spring.http.codec.max-in-memory-size=50MB
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL: define como o JPA cria/atualiza as tabelas
# 'update': cria se n\u00e3o existir, atualiza se mudar (recomendado para dev)
# 'create': cria do zero a cada execu\u00e7\u00e3o (apaga dados)
spring.jpa.hibernate.ddl-auto=update

# Opcional: mostra o SQL no console
spring.jpa.show-sql=true
